---
MXNET_VERSION: "mxnet_1.3.1_master"
output_path: "./output/rcnn/coco"
symbol: res_v1_rcnn
gpus: '0,1,2,3'
class_agnostic: false
SCALES:
- 800
- 1344
frequent: 10
kvstore: dist_device_sync
network:
  pretrained: "/hdfs/nextmsra/zhez/model/resnet50_8gpu512_philly_baseline/model-1"
  pretrained_epoch: 90
  PIXEL_MEANS:
  - 103.06
  - 115.90
  - 123.15
  PIXEL_STDS:
  - 57.375
  - 57.12
  - 58.395
  IMAGE_STRIDE: 0
  RCNN_FEAT_STRIDE: 16
  RPN_FEAT_STRIDE: 16
  FIXED_PARAMS:
  - conv0
  - bn_conv0
  - stage1
  - gamma
  - beta
  FIXED_PARAMS_SHARED:
  - conv0
  - bn_conv0
  - stage1
  - stage2
  - stage3
  - gamma
  - beta
  ANCHOR_RATIOS:
  - 0.5
  - 1
  - 2
  ANCHOR_SCALES:
  - 2
  - 4
  - 8
  - 16
  - 32
  NUM_ANCHORS: 15
  num_layers: 50
  use_dilation_on_c5: true
  use_dpool: false
  dpool_lr_mult: 0.01
  backbone_use_dconv: false
  backbone_dconv_lr_mult: 0.01
  backbone_dconv_group: 1
  backbone_dconv_start_channel: 512
dataset:
  use_zip: true
  ignore_roidb_cache: true
  num_classes: 81
  dataset: coco
  dataset_path: "/hdfs/nextmsra/hanhu/data/coco"
  image_set: train2014+valminusminival2014
#  image_set: minival2014
  root_path: "./"
  test_image_set: minival2014
  proposal: rpn
TRAIN:
  lr: 0.002
  lr_step: '0.667, 0.9'
  warmup: true
  warmup_lr: 0.0000625
  warmup_method: 'linear'
  # typically we will use 8000 warmup step for single GPU for COCO
  warmup_step: 500
  wd: 0.0002
  begin_epoch: 0
  end_epoch: 1
  model_prefix: 'rcnn_coco'
  # whether resume training
  RESUME: false
  # whether flip image
  FLIP: true
  # whether shuffle image
  SHUFFLE: true
  # whether use OHEM
  ENABLE_OHEM: false
  # size of images for each device, 2 for rcnn, 1 for rpn and e2e
  BATCH_IMAGES: 2
  # e2e changes behavior of anchor loader and metric
  END2END: true
  # group images with similar aspect ratio
  ASPECT_GROUPING: true
  # R-CNN
  # rcnn rois batch size
  BATCH_ROIS: 512
  BATCH_ROIS_OHEM: 256
  # rcnn rois sampling params
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0.0
  # rcnn bounding box regression params
  BBOX_REGRESSION_THRESH: 0.5
  BBOX_WEIGHTS:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  # RPN anchor loader
  # rpn anchors batch size
  RPN_BATCH_SIZE: 256
  # rpn anchors sampling params
  RPN_FG_FRACTION: 0.5
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_CLOBBER_POSITIVES: false
  # rpn bounding box regression params
  RPN_BBOX_WEIGHTS:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  RPN_POSITIVE_WEIGHT: -1.0
  # used for end2end training
  # RPN proposal
  CXX_PROPOSAL: true
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 12000
  RPN_POST_NMS_TOP_N: 2000
  RPN_MIN_SIZE: 0
  # approximate bounding box regression
  BBOX_NORMALIZATION_PRECOMPUTED: true
  BBOX_MEANS:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  BBOX_STDS:
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  FP16: false
  FP16_GRAD_SCALE: 128.0
  GPU_METRIC: true
TEST:
  # use rpn to generate proposal
  has_rpn: true
  # size of images for each device
  BATCH_IMAGES: 1
  # RPN proposal
  CXX_PROPOSAL: true
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  RPN_MIN_SIZE: 0
  # RPN generate proposal
  PROPOSAL_NMS_THRESH: 0.7
  PROPOSAL_PRE_NMS_TOP_N: 12000
  PROPOSAL_POST_NMS_TOP_N: 2000
  PROPOSAL_MIN_SIZE: 0
  # RCNN nms
  NMS: 0.5
  test_epoch: 1
  max_per_image: 100
